export const btnListFixed = [
  {
    label: "Line",
    resolution: "1",
    Period: 4,
    Range: 60000,
    chartType: 4,
  },
  {
    label: "15Min",
    resolution: "15",
    Period: 6,
    Range: 900000,
    chartType: 0,
  },
  {
    label: "1H",
    resolution: "60",
    Period: 8,
    Range: 3600000,
    chartType: 0,
  },
  {
    label: "4H",
    resolution: "240",
    Period: 20240,
    Range: 14400000,
    chartType: 0,
  },
  {
    label: "1D",
    resolution: "1D",
    Period: 0,
    Range: 86400000,
    chartType: 0,
  },
  {
    label: "1W",
    resolution: "1W",
    Period: 1,
    Range: 604800000,
    chartType: 0,
  },
];
export const btnList = [
  {
    label: "Line",
    resolution: "1",
    Period: 4,
    Range: 60000,
    chartType: 4,
  },
  {
    label: "1Min",
    resolution: "1",
    Period: 4,
    Range: 60000,
    chartType: 0,
  },
  {
    label: "3Min",
    resolution: "3",
    Period: 20003,
    Range: 180000,
    chartType: 0,
  },
  {
    label: "5Min",
    resolution: "5",
    Period: 5,
    Range: 300000,
    chartType: 0,
  },
  {
    label: "15Min",
    resolution: "15",
    Period: 6,
    Range: 900000,
    chartType: 0,
  },
  {
    label: "30Min",
    resolution: "30",
    Period: 7,
    Range: 1800000,
    chartType: 0,
  },
  {
    label: "1H",
    resolution: "60",
    Period: 8,
    Range: 3600000,
    chartType: 0,
  },
  {
    label: "2H",
    resolution: "120",
    Period: 20120,
    Range: 7200000,
    chartType: 0,
  },
  {
    label: "4H",
    resolution: "240",
    Period: 20240,
    Range: 14400000,
    chartType: 0,
  },
  {
    label: "6H",
    resolution: "360",
    Period: 20360,
    Range: 21600000,
    chartType: 0,
  },
  {
    label: "12H",
    resolution: "720",
    Period: 20720,
    Range: 43200000,
    chartType: 0,
  },
  {
    label: "1D",
    resolution: "1D",
    Period: 0,
    Range: 86400000,
    chartType: 0,
  },
  {
    label: "1W",
    resolution: "1W",
    Period: 1,
    Range: 604800000,
    chartType: 0,
  },
];

export const indictorMasterList = [
  { label: "MA", type: 0 },
  { label: "EMA", type: 0 },
  { label: "BOLL", type: 0 },
  // { label: 'BBI', type: 0 },
  // { label: 'ENE', type: 0 },
  // { label: "Close", type: 0, name: "关闭", showName: "主指标" },
];

export const indictorSubList = [
  { label: "MACD", type: 2 },
  { label: "KDJ", type: 2 },
  { label: "SAR", type: 2 },
  { label: "OBV", type: 2 },
  { label: "BIAS", type: 2 },
  { label: "BRAR", type: 2 },
  { label: "CCI", type: 2 },
  { label: "DMI", type: 2 },
  { label: "CR", type: 2 },
  { label: "CPSY", type: 2 },
  { label: "DMA", type: 2 },
  { label: "RSI", type: 2 },
  { label: "VR", type: 2 },
  { label: "WR", type: 2 },
  { label: "MTM", type: 2 },
  { label: "EMV", type: 2 },
  { label: "TRIX", type: 2 },
  // { label: "Close", type: 2 },
  // { label: 'BIAS' },
];
